openapi: 3.0.0
info:
  description: Traduzioni API
  version: "1.0.0"
  title: Traduzioni
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
    ####################################################################################################
    # DA FARE I PARAMETRI DELLE CHIAMATE
########################################################################################################
tags:
  - name: superadmin
    description: operazioni che possono essere eseguite da Zero12
  - name: admin
    description: operazioni che possono essere eseguite dagli admin del tenant
  - name: traduttori
    description: operazioni che possono essere eseguite dai traduttori
    
########################################################################################################
paths:
  /login:
    get:
      tags:
        - admin
        - superadmin
        - traduttori
      summary: searches inventory
      operationId: searchInventory
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      parameters:
        - in: query
          name: searchString
          description: pass an optional search string for looking up inventory
          required: false
          schema:
            type: string
        - in: query
          name: skip
          description: number of records to skip for pagination
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          description: maximum number of records to return
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses: #######DA FARE
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Traduzione'
        '400':
          description: bad input parameter
        
  /{NomeTenant}/translation:
    get:
        tags:
          - admin
          - superadmin
          - traduttori
        summary: ottenere la lista delle traduzioni in un determinato tenant
        operationId: getAllTranslations
        description: |
          ottenere la lista delle traduzioni in un determinato tenant
        parameters:
          - in: path
            name: NomeTenant
            description: ottenere la lista delle traduzioni in un determinato tenant
            required: true
            schema:
              type: string
        responses:  #######DA FARE
          '200':
            description: si ottiene una lista di traduzioni in particolare chiavetraduzione traduzionedefault
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Traduzione'
                  ## meta -> /tenant1/translation?page=2 
          '400':
            description: tenant non esistente
            
            
  /{NomeTenant}/translation/{chiaveTraduzione}:
    get:
        tags:
          - admin
          - superadmin
          - traduttori
        summary: ottenere una traduzione specifica dal tenant
        operationId: getTranslation
        description: |
          ottenere una traduzione specifica dal tenant
        parameters:
          - in: path
            name: NomeTenant
            description: nome del tenant
            required: true
            schema:
              type: string
          - in: path
            name: chiaveTraduzione
            description: chiave traduzione
            required: true
            schema:
              type: string
        responses: #######DA FARE
          '200':
            description: search results matching criteria
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Traduzione'
          '400':
            description: bad input parameter
    put:
      tags:
          - admin
          - superadmin
          - traduttori
      summary: aggiungere una traduzione al tenant
      operationId: addTranslation
      description: aggiungere una traduzione al tenant
      parameters:
          - in: path
            name: NomeTenant
            description: nome del tenant
            required: true
            schema:
              type: string
          - in: path
            name: chiaveTraduzione
            description: chiave traduzione
            required: true
            schema:
              type: string
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody: #######DA FARE
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OggettoTraduzione'# faccio un oggetto con meno campi, solo quelli essenziali: esempio: non modifico la chiavetraduzione
        description: Inventory item to add
        
  /{NomeTenant}:
    get:
      tags:
        - traduttori
        - admin
        - superadmin
      summary: ottenere infomazioni specifiche del tenant
      operationId: getTenantInfo
      description: |
        ottenere infomazioni specifiche del tenant
      parameters:
        - in: path
          name: NomeTenant
          description: nome del tenant
          required: true
          schema:
            type: string
      responses: #######DA FARE
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                oneOf: ## utente deve vedere solo alcune cose... non i dettagli di altri utenti
                type: array
                items:
                  $ref: '#/components/schemas/Traduzione'
        '400':
          description: bad input parameter
      
      put: ##creazione/modifica tenant
        tags:
          - superadmin
        summary: 
        operationId: 
        description:
        parameters:
          - in: path
            name: NomeTenant
            description: nome del tenant
            required: true
            schema:
              type: string
    delete:
      tags:
        - superadmin
      parameters:
        - in: path
          name: NomeTenant
          description: nome del tenant
          required: true
          schema:
            type: string
      #responses: #######DA FARE
      #  '200':
      #    description: ---
      #    content:
      #      application/json:
      #        schema:
      #          type: array
      #          items:
      #  '400':
      #    description: bad input parameter

  /{NomeTenant}/invite: ## invito traduttori nel tenant > cognito
    post:
      tags:
        - admin
        - superadmin
      summary: ---
      operationId: ---
      description: ---
      parameters:
        - in: path
          name: NomeTenant
          description: nome del tenant
          required: true
          schema:
            type: string
        
  /{NomeTenant}/user: ##crea un utente, chiamata in cascata dopo la creazione del tenant eseguito solo dal supertenant
    post:
      tags: 
        - superadmin
      summary: 
      operationId: 
      description:
    delete:
      tags:
        - admin
        - superadmin
        
  
    
        
  /Tenants:  ## lista di tutti i tenant visibili al super admin
    get:
      tags:
        - superadmin
      
   
          
################################################################################################
components:
  schemas:
    # oggetto traduzione (es: en:hi, it:ciao)
    OggettoTraduzione:
      type: object
      required: 
        - traduzione
      properties:
        traduzione:
          type: object
          additionalProperties:
            type: string
          example:
            en: Hello
            it: Ciao
      
        lingueTraduzione:
          type: array
          items:
            type: string
        modificatodaUtente:
          type: string
          example: utente1
        dataCreazione:
          type: string
          example: 2023-05-02
          
        
    ## traduzione che viene visualizzata nella schermata generale(lista di traduzioni)
    Traduzione:
      type: object
      required:
        - keyTraduzione
        - traduzioneDefault
      properties:
        keyTraduzione:
          type: string
          example: trad1
        linguaTraduzioneDefault:
          type: string
          example: it  
        traduzioneinLinguaDefault:
          type: string
          example: ciao
        additionalProperties:
          anyOf:
            - $ref: '#/components/schemas/OggettoTraduzione' ## serve per riutilizzare l'oggetto traduzioni
            - $ref: '#/components/schemas/VersioniTraduzione'
    
    VersioniTraduzione:
      type: object
      properties:
        modificatodaUtente:
          type: string
          example: utente1
        dataModifica:
          type: string
        traduzioni:
          type: string
          example:
            en: Hello
            it: Ciao
    
    Tenant:
      type: object
      properties:
        nomeTenant:
          type: string
          example: tenant1
        numeroTraduzioniDisponibili:
          type: integer
          minimum: 0
        numeroTraduzioniUsate:
          type: integer
          minimum: 0
        token:
          type: string
        listaUserTenant:
          type: array
          items:
            $ref: '#/components/schemas/User'
    
    User:
      type: object
      properties:
        emailUtente:
          type: string
        username:
          type: string
        dataCreazioneUtente:
          type: string
    
    