########################
## APRIRE CON https://editor.swagger.io/
########################
openapi: 3.0.0
info:
  description: Traduzioni API
  version: "0.0.1"
  title: Traduzioni
  contact:
    email: submarines.g4@gmail.com
tags:
  - name: superadmin
    description: operazioni che possono essere eseguite da Zero12
  - name: admin
    description: operazioni che possono essere eseguite dagli admin del tenant
  - name: traduttori
    description: operazioni che possono essere eseguite dai traduttori
    
########################################################################################################
paths:
  /login:
    get: #######DA FARE
      tags:
        - admin
        - superadmin
        - traduttori
      summary: login
      operationId: login
      description: login
      responses:
        '200':
          description: login autorizzato
        '400':
          description: login NON autorizzato
        
  /{tenantId}/translations:
    get:
        tags:
          - admin
          - superadmin
          - traduttori
        summary: ritorna la lista delle traduzioni in un determinato tenant
        operationId: getAllTranslations
        description: |
          ottenere la lista delle traduzioni in un determinato tenant
        parameters:
          - in: path
            name: tenantId
            description: ritorna la lista delle traduzioni in un determinato tenant
            required: true
            schema:
              type: string
        responses:
          '200':
            description: si ottiene una lista di traduzioni in particolare chiavetraduzione traduzionedefault
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    translations:
                      type: array
                      items:
                        $ref: '#/components/schemas/Traduzione'
          '400':
            description: bad input parameter
          '404':
            description: not found
          '500':
            description: internal server error
            
            
            
  /{tenantId}/translation/{TranslationKey}:
    get:
        tags:
          - admin
          - superadmin
          - traduttori
        summary: ritorna il dettaglio della traduzione
        operationId: getTranslation
        description: |
          ritorna il dettaglio della traduzione
        parameters:
          - in: path
            name: tenantId
            description: nome del tenant
            required: true
            schema:
              type: string
          - in: path
            name: TranslationKey
            description: chiave traduzione
            required: true
            schema:
              type: string
        responses: #######DA FARE
          '200':
            description: search results matching criteria
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    modificationDate:
                      type: string
                      example: 2023-05-20T11:51:24.708Z
                    translations:
                      type: array
                      items:
                        type: object
                        properties:
                          language:
                            type: string
                            example: en
                          content:
                            type: string
                            example: hello
                    defaultTranslationinLanguage:
                      type: string
                      example: hello
                    defaultTranslationLanguage:
                      type: string
                      example: en
                    keySort:
                      type: string
                      example: homeScreenGreeting
                    published:
                      type: boolean
                      example: false
                    creationDate:
                      type: string
                      example: 2023-05-20T11:51:24.708Z
                    modifiedbyUser:
                      type: string
                      example: test1
                    versionedTranslations:
                      items:
                        $ref: '#/components/schemas/Version'
          '400':
            description: bad input parameter
          '404':
            description: not found
          '500':
            description: internal server error

    put:
      tags:
          - admin
          - superadmin
          - traduttori
      summary: aggiungere una traduzione al tenant
      operationId: addTranslation
      description: aggiungere una traduzione al tenant
      parameters:
          - in: path
            name: tenantId
            description: nome del tenant
            required: true
            schema:
              type: string
          - in: path
            name: TranslationKey
            description: chiave traduzione
            required: true
            schema:
              type: string
      responses:
        '201':
          description: item created
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    newTranslation:
                      type: object
                      properties:
                        tenantId:
                          type: string
                          example: tenant1
                        keySort:
                          type: string
                          example: trad1
                        defaultTranslationinLanguage:
                          type: string
                          example: hello
                        defaultTranslationLanguage:
                          type: string
                          example: en
                        modifiedbyUser:
                          type: string
                          example: test1
                        translations:
                          type: array
                          items:
                            type: object
                            properties:
                              language:
                                type: string
                                example: en
                              content:
                                type: string
                                example: hello
                        creationDate:
                          type: string
                          example: 2023-05-20T11:51:24.708Z
                        modificationDate:
                          type: string
                          example: 2023-05-20T11:51:24.708Z
                        published:
                          type: boolean
                          example: false
                        versionedTranslations:
                          items:
                            $ref: '#/components/schemas/Version'
        '400':
          description: 'invalid input, object invalid'
        '500':
          description: internal server error
      requestBody: #######DA FARE
        content:
          application/json:
            schema:
              type: object
              properties:
                defaultTranslationinLanguage:
                  type: string
                  example: hello
                defaultTranslationLanguage:
                  type: string
                  example: en
                modifiedbyUser:
                  type: string
                  example: test1
                translations:
                  type: array
                  items:
                    type: object
                    properties:
                      language:
                        type: string
                        example: en
                      content:
                        type: string
                        example: hello
        description: Inventory item to add
    
    delete:
      tags:
        - admin
        - superadmin
        - traduttori
      summary: eliminare una traduzione dal tenant
      operationId: deleteTranslation
      description: eliminare una traduzione dal tenant
      parameters:
          - in: path
            name: tenantId
            description: nome del tenant
            required: true
            schema:
              type: string
          - in: path
            name: TranslationKey
            description: chiave traduzione
            required: true
            schema:
              type: string
      responses:
        '200':
          description: OK
        '404':
          description: not found
        '500':
          description: internal server error
        
  /{tenantId}: ##DEFINITIVO
    get:
      tags:
        - traduttori
        - admin
        - superadmin
      summary: ottenere infomazioni specifiche del tenant
      operationId: getTenantInfo
      description: |
        ottenere infomazioni generali del tenant, si usa nella schermata delle informazioni riguradanti il tenant
      parameters:
        - in: path
          name: tenantId
          description: nome del tenant
          required: true
          schema:
            type: string
      responses: #######DA FARE
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: object
                properties:
                  tenantName:
                    type: string
                    example: tenant1
                  numberTranslationAvailable:
                    type: integer
                    example: 1000
                  numberTranslationUsed:
                    type: integer
                    example: 0
                  defaultTranslationLanguage:
                    type: string
                    example: it
                  listAvailableLanguages:
                    type: array
                    items:
                      type: string
                    example: ["it","en"]
                  token:
                    type: string
                  userList:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
        '400':
          description: bad input parameter
        '404':
          description: object not found
        '500':
          description: internal server error
    
    
      
    put: ##creazione/modifica tenant
      tags:
        - superadmin
      summary: creazione e/o modifica di un tenant
      operationId: createTenant
      description: creazione e/o modifica di un tenant
      parameters:
        - in: path
          name: tenantId
          description: nome del tenant
          required: true
          schema:
            type: string
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  tenantName:
                    type: string
                    example: tenant1
                  numberTranslationAvailable:
                    type: integer
                    example: 1000
                  numberTranslationUsed:
                    type: integer
                    example: 0
                  defaultTranslationLanguage:
                    type: string
                    example: it
                  listAvailableLanguages:
                    type: array
                    items:
                      type: string
                    example: ["it","en"]
                  token:
                    type: string
                  userList:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  tenantName:
                    type: string
                    example: tenant1
                  numberTranslationAvailable:
                    type: integer
                    example: 1000
                  numberTranslationUsed:
                    type: integer
                    example: 0
                  defaultTranslationLanguage:
                    type: string
                    example: it
                  listAvailableLanguages:
                    type: array
                    items:
                      type: string
                    example: ["it","en"]
                  token:
                    type: string
                  userList:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
        '400':
          description: 'Bad Request: invalid input, object invalid'
        '500':
          description: internal server error
      requestBody: 
        content:
          application/json:
            schema:
              allOf: ## utente deve vedere solo alcune cose... non i dettagli di altri utenti
                - $ref: '#/components/schemas/TenantInfoGenerali'
        description: Inventory item to add
        ## CHIEDERE SE FARE UNO SCHEMA SOLO PER LA PUT (SENZA INVIARE CAMPI VUOTI)
        
    delete:
      tags:
        - superadmin
      summary: cancellazione di un tenant
      operationId: deleteTenant
      description: cancellazione di un tenant
      parameters:
        - in: path
          name: tenantId
          description: nome del tenant
          required: true
          schema:
            type: string
      responses:
          '200':
            description: OK
          '404':
            description: not found
          '500':
            description: internal server error

  /{tenantId}/invite: ## invito traduttori nel tenant > cognito
    post:
      tags:
        - admin
        - superadmin
      summary: invito traduttori nel tenant
      operationId: inviteUser
      description: invito traduttori nel tenant
      parameters:
        - in: path
          name: tenantId
          description: nome del tenant
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userEmail:
                  type: string
                  example: test1@gmail.com
                username:
                  type: string
                  example: test1
                name:
                  type: string
                  example: Mario
                lastName:
                  type: string
                  example: Rossi
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf: ## utente deve vedere solo alcune cose... non i dettagli di altri utenti
                  - $ref: '#/components/schemas/User'
        '400':
          description: bad request  
        '500':
          description: internal server error

  /tenants:  ## lista di tutti i tenant visibili al super admin
    get:
      tags:
        - superadmin
      summary: ottenere lista di tutti i tenant
      operationId: getAllTenant
      description: |
        ottenere lista di tutti i tenant
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: object
                properties:
                  tenants:
                    type: array
                    items:
                      type: object
                      properties:
                        tenantName:
                          type: string
                          example: tenant1
                        numberTranslationAvailable:
                          type: integer
                          example: 1000
                        numberTranslationUsed:
                          type: integer
                          example: 0
                        defaultTranslationLanguage:
                          type: string
                          example: it
        '404':
          description: not found
        '500':
          description: internal server error

################################################################################################
components:
  schemas:
    
    # oggetto traduzione (es: en:hi, it:ciao)
    OggettoTraduzione:
      type: object
      required: 
        - traduzione
      properties:
      # contiene tutte le lingue del tenant anche quelle che non hanno una traduzione
        translations:
          type: array
          items:
            type: object
            properties:
              language:
                type: string
                example: it
              content:
                type: string
                example: ciao
          example:
            - {"language":it, "content":ciao}
            - {"language":en, "content":hi}
            - {"language":fr, "content":}
        modifiedbyUser:
          type: string
          example: utente1
        creationDate:
          type: string
          example: 2023-05-02
        modificationDate:
          type: string
          example: 2023-06-02
        published:
          type: boolean
          example: false
          
        
    ## traduzione che viene visualizzata nella schermata generale(lista di traduzioni)
    Traduzione:
      type: object
      required:
        - keyTraduzione
        - traduzioneDefault
      properties:
        translationKey:
          type: string
          example: trad1
        defaultTranslationLanguage:
          type: string
          example: it  
        defaultTranslationinLanguage:
          type: string
          example: ciao

    VersioniTraduzione:
      type: object
      properties:
        versionedTranslations:
          type: array
          items:
            $ref: '#/components/schemas/Version'

    Version:
      type: object
      properties:
        modifiedbyUser:
          type: string
          example: utente1
        modificationDate:
          type: string
          example: 2023-06-10
        translations:
          type: array
          items:
            type: object
            properties:
              language:
                type: string
                example: it
              content:
                type: string
                example: ciao
          example:
            - {"language":it, "content":ciaoo}
            - {"language":en, "content":hello}
    
    TenantInfoGenerali:
      type: object
      properties:
        tenantName:
          type: string
          example: tenant1
        numberTranslationAvailable:
          type: integer
          minimum: 0
        defaultTranslationLanguage:
          type: string
          example: it
        listAvailableLanguages:
          type: array
          items:
            type: string
          example: ["it","en"]
        
    
    TenantInfoSensibili:
      type: object
      properties:
        token:
          type: string
        userList:
          type: array
          items:
            $ref: '#/components/schemas/User'
    
    User:
      type: object
      properties:
        userEmail:
          type: string
        username:
          type: string
        creationDate:
          type: string
        name:
          type: string
        lastName:
          type: string
    